import type { Metadata } from "next";
import "@/styles/globals.css";
import InactivityTracker from "@/components/InactiveTracker";
import { ToastContainer } from "@/components/Toast/ToastContainer"
import React from "react";
import { Outfit } from 'next/font/google';
import { FaWhatsapp } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Renstra Stikom PGRI Banyuwangi", 
  description: "Generated by create next app",
};

// Initialize the font
const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}>
      <body>
          <InactivityTracker />
          {children}
          <ToastContainer />
          
          {/* Floating WhatsApp Button */}
          <div className="fixed bottom-6 right-6 z-50">
            <a 
              href="https://wa.me/6285784161309" // Ganti dengan nomor CS Anda
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center w-14 h-14 bg-green-500 rounded-full shadow-lg hover:bg-green-600 transition-colors duration-300"
              aria-label="Hubungi Customer Service via WhatsApp"
            >
              <FaWhatsapp className="text-white text-2xl" />
            </a>
          </div>
      </body>
    </html>
  );
}