import type { Metadata } from "next";
import "@/styles/globals.css";
import InactivityTracker from "@/components/InactiveTracker";
import { ToastContainer } from "@/components/Toast/ToastContainer"
import React from "react";
import { Outfit } from 'next/font/google';

export const metadata: Metadata = {
  title: "Renstra Stikom PGRI Banyuwangi", 
  description: "Generated by create next app",
};


// Initialize the font
const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.className}>
      <body>
          <InactivityTracker />
          {children}
          <ToastContainer />
      </body>
    </html>
  );
}