import type { Metadata } from "next";
import "@/styles/globals.css";
import InactivityTracker from "@/components/InactiveTracker";
import { ToastContainer } from "@/components/Toast/ToastContainer"
// import { AuthProvider } from "@/contexts/AuthContext";
import React from "react";
export const metadata: Metadata = {
  title: "Renstra Stikom PGRI Banyuwangi", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <InactivityTracker />
          {children}
          <ToastContainer />
      </body>
    </html>
  );
}
